monarch-initiative/embiggen

- n2v/hetnode2vec.py
- tests/test_node2vec.py
Fix a unit test broken when adding multiprocessor support
> Fix unit tests

- n2v/word2vec.py
**text_encoder.py**
- Performed light refactoring of code, which included fixing small bugs
- Cleaned up the documentation of class attributes and methods to be a bit more in line with Google's style
**word2vec.py**
- Added `y = tf.cast(y, tf.int64)` to `get_loss()` 
- Converted several instances of `dtype=np.int32` to `tf.int64`
> Refactor and repair

- runAnalysis.py
Per @pnrobinson's request [here](https://github.com/TheJacksonLaboratory/N2V/issues/29)
> Write more meaningful error message when first arg isn't a command

- n2v/__init__.py
- n2v/word2vec.py
- tests/test_word2vec.py
still work in progress but isolated
> Cbow list of lists

- setup.py
- xn2v/text_encoder.py
Badly named branch - this PR is requesting to merge commits made to the following files:
**setup.py** 
- added `click` library to requirements
**xn2v/text_encoder.py**  
- Improved text cleaning to remove ascii and non-ascii punctuation
> Refactor word2vec

- testK.py
- xn2v/__init__.py
- xn2v/kW2V.py
@callahantiff  This class just adds some very prototype code for keras-style word2vec, just for testing. Please accept the PR after you have seen it, it is just a new file and does not interfere with anything else. This is the kind of code we will need to write, I think, to use the keras classes.
> Adding prototype file for keras word2vec

- xn2v/text_encoder.py
- xn2v/word2vec.py
Improving on the previous PR and fixes tests.
But given @callahantiff 's suggestion of alternatives https://github.com/monarch-initiative/N2V/issues/45#issuecomment-580904394, we should make a call on whether we should go down the Keras route or ktext.
> Improve keras implementation

- tests/test_batcher.py
- xn2v/__init__.py
- xn2v/csf_graph/csf_graph.py
- xn2v/w2v/__init__.py
- xn2v/w2v/skip_gram_batcher.py
Trying to pull everything together. Here are two new classes for batching. We still will need to make the Batcher classes more homogeneous (e.g., window_size means the same thing s skip_window in the two constructors). The classes can be used instead of the methods in the current implementations. We would need two more classes for all combinations of SG/CBOW list/list-of-list
> Skip gram batcher

- runLinkPrediction_ppi.py
- xn2v/link_prediction.py
- xn2v/word2vec.py
Adding `assert  tf.__version__ >= "2.0"` to check version of tensorflow and some small edits.
> Check tensorflow version is greater than 1

- runLinkPrediction_ppi.py
@pnrobinson Cleaned up runLinkPrediction_ppi.py and added parse_args() to parse parameters of node2vec (p,q,gamma,....) and link prediction.
> parser for arguments of node2vec and link prediction

- .travis.yml
- setup.py
- xn2v/hetnode2vec.py
- xn2v/word2vec.py
Luca suggested a while ago that we do this, thought I'd make a PR while I'm thinking of it
> Changed progress print statement to tdqm() calls per Luca's suggestion

- xn2v/text_encoder.py
Moving Luca's improvements from [this PR](https://github.com/monarch-initiative/N2V/pull/97) here, to avoid rebase hell. 
Note that I'm omitting his edits to `xn2v/xn2v_parser.py` b/c this file doesn't exist in `develop`
> Add luca's improvements to text_encoder

- xn2v/hetnode2vec.py
Should shave off a little runtime
> Parallelize random walks

- xn2v/word2vec.py
adjusting calculating of vocabulary size
> adding named arguments to calling word2vec super class.

- runLinkPrediction_ppi.py
- xn2v/hetnode2vec.py
- xn2v/link_prediction.py
- xn2v/link_prediction_functions.py
- xn2v/word2vec.py
Various fixes made at the hackathon to find the culprit for the low ROC score #135
> Hackathon fixes

- runLinkPrediction_ppi.py
- xn2v/__init__.py
- xn2v/coocurrence_encoder.py
- xn2v/glove.py
This PR just adjusts the constructor of the GloVe class to work with the rest of N2V. These are the results on the small demo graph. You can now run this with the runLinkPrediction_ppi.py script
[INFO]: Total edges of training graph: 528
[INFO]: Training edges (negative): 530
[INFO]: Test edges (positive): 132
[INFO]: Test edges (negative): 134
predictions for training set:
confusion matrix (training): [[422 108]
[ 96 432]]
Accuracy (validation) : 0.8071833648393195
Specificity (validation): 0.7962264150943397
Sensitivity (validation): 0.8181818181818182
F1-score (validation): 0.8089887640449438
node2vec Train ROC score (training): 0.8884505431675244
node2vec Train AP score (training): 0.8921310984934154
predictions for test set:
confusion matrix (test): [[60 74]
[36 96]]
Accuracy (test): …
> adjusting GloVe interface for training from RW

- tests/test_word2vec.py
Just a little nano-PR to fix failing test (bad file path)
> Fix test file path causing failing test

- README.rst
- docs/source/code.rst
- docs/source/index.rst
- docs/source/running.rst
- docs/source/word2vec.rst
New README and new instructions for word2vec
> Documentation

- embiggen/word2vec.py
to address #185 
@pnrobinson @callahantiff
> remove unnecessary loop

- embiggen/graph/graph_factory.py
- embiggen/graph/numba_graph.py
- embiggen/graph/random_walks.py
- tests/test_embiggen.py
- tests/test_graph.py
> Multigraph

- embiggen/word2vec.py
- runAnalysis.py
- runLinkPrediction_ppi.py
Fixing display word issue. Possibly some additional work is needed but it is working now
https://github.com/monarch-initiative/embiggen/issues/187
> fixing display word.

- embiggen/edge_prediction/edge_prediction_model.py
- embiggen/embedders/ensmallen_embedders/deepwalk_cbow.py
- embiggen/embedders/ensmallen_embedders/deepwalk_glove.py
- embiggen/embedders/ensmallen_embedders/deepwalk_skipgram.py
- embiggen/embedders/ensmallen_embedders/first_order_line.py
- embiggen/embedders/ensmallen_embedders/node2vec_cbow.py
- embiggen/embedders/ensmallen_embedders/node2vec_glove.py
- embiggen/embedders/ensmallen_embedders/node2vec_skipgram.py
- embiggen/embedders/ensmallen_embedders/second_order_line.py
- embiggen/embedders/ensmallen_embedders/siamese_model.py
- embiggen/embedders/ensmallen_embedders/structured_embedding.py
- embiggen/embedders/ensmallen_embedders/transe.py
- embiggen/embedders/ensmallen_embedders/unstructured.py
- embiggen/embedders/ensmallen_embedders/walklets.py
- embiggen/embedders/ensmallen_embedders/walklets_cbow.py
- embiggen/embedders/ensmallen_embedders/walklets_glove.py
- embiggen/embedders/ensmallen_embedders/walklets_skipgram.py
- embiggen/utils/abstract_models/abstract_classifier_model.py
Integrated support of mixed precision for all Ensmallen models.
> Mixed precision
